# Catppuccin

spacing = 2

padding = 1

hide_ascii = true

separator = ""

key_color = "#CBA6F7"

separator_color = "#B4BEFE"


[palette]

visible = true

type = "Full"

glyph = "  "


[bar]

visible = false

glyph = ""

symbol_open = '('

symbol_close = ')'


[box]

visible = true

title = " Catppuccin Mocha"

border = "round"


[box.inner_margin]

x = 1

y = 1
